name: Dependency Check Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore .NET Dependencies
        run: dotnet restore CodeOptimization/CodeOptimization.sln

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'CodeOptimization'
          path: './'
          format: 'ALL'
          out: 'dependency-check-report'
          args: >
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --disableOssIndex

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report/
