name: OWASP Dependency-Check
on:
  workflow_dispatch:
    # This allows the n8n workflow to trigger this manually
 
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
 
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        id: dep-check
        with:
          project: 'My-Project'
          path: '.'
          format: 'JSON'
          out: 'reports'
          args: '--scan'
 
      - name: Upload Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.json
