name: Dependency Vulnerability Scan

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - 'release/**'

jobs:
  scan:
    name: Scan Dependencies for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Restore .NET packages
        run: dotnet restore CodeOptimization/CodeOptimization.csproj

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install other dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f pom.xml ]; then
            mvn install -DskipTests
          fi

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: CodeOptimization
          scan: 'CodeOptimization/'
          format: 'ALL'
          out: 'dependency-check-report'
          fail-on-cvss: '7'

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: dependency-check-report

      - name: Print summary
        run: |
          echo "Vulnerability scan completed."
          echo "Check the uploaded artifact: dependency-check-report"
