name: Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-scan:
    name: Run Dependency-Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: CodeOptimization
          path: ./                  # Folder to scan
          format: ALL               # Generates HTML, XML, JSON, CSV reports
          out: dependency-check-report
          args: >
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --noupdate
            --disableOssIndex

      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: dependency-check-report/
