name: Scan Dependencies for Vulnerabilities

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'CodeOptimization'
          path: './'                         # directory to scan
          format: 'ALL'                      # report formats: HTML, XML, JSON, CSV
          out: 'dependency-check-report'
          args: '--nvdApiKey ${{ secrets.NVD_API_KEY }} --ossindexUser ${{ secrets.OSS_INDEX_USER }} --ossindexPassword ${{ secrets.OSS_INDEX_PASSWORD }}'

      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
