name: Dependency Vulnerability Scan

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - 'release/**'

jobs:
  scan:
    name: Scan Dependencies for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET packages
        run: dotnet restore

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: MyCSharpApp
          scan: .
          format: "JSON"
          out: "dependency-check-report"

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: dependency-check-report/dependency-check-report.json

      - name: Print summary
        run: |
          echo "Vulnerability scan completed."
          echo "Check the uploaded artifact: dependency-check-report/dependency-check-report.json"
