name: Scan Dependencies for Vulnerabilities

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-scan:
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Setup .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # Run OWASP Dependency Check
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          scan: './'                        # directory to scan
          project: 'CodeOptimization'       # project name
          format: 'ALL'                     # report formats: HTML, XML, JSON, CSV
          out: 'dependency-check-report'    # output folder
          fail-on-error: 'true'             # fail workflow on CVEs
          nvd-api-key: ${{ secrets.NVD_API_KEY }}

      # Upload Dependency Check Reports
      - name: Upload Dependency-Check Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
