name: Dependency Check Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-scan:
    runs-on: ubuntu-24.04

    steps:
      # Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # Restore dependencies
      - name: Restore .NET Dependencies
        run: dotnet restore CodeOptimization/CodeOptimization.sln

      # Build project
      - name: Build Project
        run: dotnet build CodeOptimization/CodeOptimization.sln -c Debug

      # Ensure output folder exists
      - name: Prepare output folder
        run: mkdir -p dependency-check-report

      # Run Dependency-Check
      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'CodeOptimization'
          # Scan the built binaries instead of the raw NuGet cache
          path: './CodeOptimization/bin/Debug/net8.0'
          format: 'ALL'
          out: 'dependency-check-report'
          args: >
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
            --enableExperimental
            --update
            --disableOssIndex

      # Debug: show what was generated
      - name: Show report folder
        run: ls -R dependency-check-report

      # Upload the report as artifact
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
