name: Dependency Check Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-scan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          DISABLE_OSSINDEX: true            # Disable OSS Index
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        with:
          project: 'CodeOptimization'
          path: './'
          format: 'ALL'
          out: 'dependency-check-report'
          args: '--nvdApiKey $NVD_API_KEY --noupdate'

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
