name: Dependency Check Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-scan:
    runs-on: ubuntu-24.04

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      # 3️⃣ Restore dependencies
      - name: Restore .NET Dependencies
        run: dotnet restore CodeOptimization/CodeOptimization.sln

      # 4️⃣ Build project
      - name: Build project
        run: dotnet build CodeOptimization/CodeOptimization.sln -c Debug

      # 5️⃣ List built binaries (debugging)
      - name: List built binaries
        run: ls -R CodeOptimization/bin/Debug/net8.0

      # 6️⃣ Prepare output folder
      - name: Prepare output folder
        run: mkdir -p dependency-check-report

      # 7️⃣ Install Dependency-Check CLI
      - name: Install Dependency-Check CLI
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.3.3/dependency-check-8.3.3-release.zip
          unzip dependency-check-8.3.3-release.zip -d dependency-check
          chmod +x dependency-check/dependency-check/bin/dependency-check.sh

      # 8️⃣ Run Dependency-Check CLI
      - name: Run Dependency-Check
        run: |
          ./dependency-check/dependency-check/bin/dependency-check.sh \
            --scan ./CodeOptimization/bin/Debug/net8.0 \
            --format ALL \
            --out dependency-check-report \
            --nvdApiKey ${{ secrets.NVD_API_KEY }} \
            --enableExperimental \
            --update \
            --disableOssIndex

      # 9️⃣ Show report folder
      - name: Show report folder
        run: ls -R dependency-check-report

      # 🔟 Upload Dependency-Check Report
      - name: Upload Dependency-Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
