name: Dependency Vulnerability Scan

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
      - 'release/**'

jobs:
  scan:
    name: Scan Dependencies for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js (if using npm)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm install
          fi
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f pom.xml ]; then
            mvn install -DskipTests
          fi

      - name: Run GitHub Security Advisory Scan
        run: |
          echo "Checking for Dependabot alerts via GitHub API..."
          curl -s -H "Accept: application/vnd.github+json" \
               -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
               https://api.github.com/repos/${{ github.repository }}/vulnerability-alerts \
               > vulnerability_report.json

      - name: Upload Vulnerability Report
        uses: actions/upload-artifact@v4
        with:
          name: vulnerability-report
          path: vulnerability_report.json

      - name: Print summary
        run: |
          echo "Vulnerability scan completed."
          echo "Check the uploaded artifact: vulnerability_report.json"
